    # time.sleep(5)
    # tilt_body(pitch_roll_setpoint, pitch_roll_setpoint_lock, tilt_angle, -tilt_angle)
    # time.sleep(delay)
    # set_swing_legs(swinging_legs, swinging_legs_lock, [0])  # If leg 0 is swinging
    # walk(foot_positions, [0], 0, STEP_LENGTH_Y,foot_positions_lock)
    # time.sleep(walk_delay)
    # walk(foot_positions, [0], -STEP_LENGTH_X, 0,foot_positions_lock)
    # walk(foot_positions, [1,2,3], STEP_LENGTH_X/4, 0,foot_positions_lock)
    # time.sleep(walk_delay)
    # walk(foot_positions, [0], 0, -STEP_LENGTH_Y,foot_positions_lock)
    # time.sleep(walk_delay)
    # tilt_body(pitch_roll_setpoint, pitch_roll_setpoint_lock, 0, 0)
    # set_swing_legs(swinging_legs, swinging_legs_lock, [])
    # time.sleep(delay)

    # tilt_body(pitch_roll_setpoint, pitch_roll_setpoint_lock, -tilt_angle, tilt_angle)
    # time.sleep(delay)
    # set_swing_legs(swinging_legs, swinging_legs_lock, [3])  # If leg 3 is swinging
    # walk(foot_positions, [3], 0, STEP_LENGTH_Y,foot_positions_lock)
    # time.sleep(walk_delay)
    # walk(foot_positions, [3], -STEP_LENGTH_X, 0,foot_positions_lock)
    # walk(foot_positions, [0,1,2], STEP_LENGTH_X/4, 0,foot_positions_lock)
    # time.sleep(walk_delay)
    # walk(foot_positions, [3], 0, -STEP_LENGTH_Y,foot_positions_lock)
    # time.sleep(walk_delay)
    # tilt_body(pitch_roll_setpoint, pitch_roll_setpoint_lock, 0, 0)
    # set_swing_legs(swinging_legs, swinging_legs_lock, [])
    # time.sleep(delay)

    # tilt_body(pitch_roll_setpoint, pitch_roll_setpoint_lock, tilt_angle, tilt_angle)   #HAVE TO CHECK CONFUSED  
    # time.sleep(delay)
    # set_swing_legs(swinging_legs, swinging_legs_lock, [1])  # If leg 1 is swinging
    # walk(foot_positions, [1], 0, STEP_LENGTH_Y,foot_positions_lock)
    # # time.sleep(walk_delay)
    # walk(foot_positions, [1], -STEP_LENGTH_X, 0,foot_positions_lock)
    # walk(foot_positions, [0,2,3], STEP_LENGTH_X/4, 0,foot_positions_lock)
    # time.sleep(walk_delay)
    # walk(foot_positions, [1], 0, -STEP_LENGTH_Y,foot_positions_lock)
    # time.sleep(walk_delay)
    # tilt_body(pitch_roll_setpoint, pitch_roll_setpoint_lock, 0, 0)
    # set_swing_legs(swinging_legs, swinging_legs_lock, [])
    # time.sleep(delay)


    # tilt_body(pitch_roll_setpoint, pitch_roll_setpoint_lock, -tilt_angle, -tilt_angle)
    # time.sleep(delay)
    # set_swing_legs(swinging_legs, swinging_legs_lock, [2])  # If leg 2 is swinging
    # walk(foot_positions, [2], 0, STEP_LENGTH_Y,foot_positions_lock)
    # # time.sleep(walk_delay)
    # walk(foot_positions, [2], -STEP_LENGTH_X, 0,foot_positions_lock)
    # walk(foot_positions, [0,1,3], STEP_LENGTH_X/4, 0,foot_positions_lock)
    # time.sleep(walk_delay)
    # walk(foot_positions, [2], 0, -STEP_LENGTH_Y,foot_positions_lock)
    # time.sleep(walk_delay)
    # tilt_body(pitch_roll_setpoint, pitch_roll_setpoint_lock, 0, 0)
    # set_swing_legs(swinging_legs, swinging_legs_lock, [])
    # time.sleep(delay)